/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_catchball_CatchBallRenderer */

#ifndef _Included_net_catchball_CatchBallRenderer
#define _Included_net_catchball_CatchBallRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_catchball_CatchBallRenderer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_catchball_CatchBallRenderer_nativeInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_catchball_CatchBallRenderer
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_catchball_CatchBallRenderer_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_catchball_CatchBallRenderer
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_catchball_CatchBallRenderer_nativeRender
  (JNIEnv *, jclass);

/*
 * Class:     net_catchball_CatchBallGLSurface
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_catchball_CatchBallGLSurface_nativePause
  (JNIEnv *, jclass);

/*
 * Class:     net_catchball_CatchBallGLSurface
 * Method:    processTouch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_catchball_CatchBallGLSurface_processTouch
  (JNIEnv *, jclass, jfloat x1, jfloat y1, jfloat x2, jfloat y2);

#ifdef __cplusplus
}
#endif
#endif
